---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accesskeys.deuxfleurs.fr
spec:
  group: deuxfleurs.fr
  names:
    categories: []
    kind: AccessKey
    plural: accesskeys
    shortNames: []
    singular: accesskey
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: owning bucket instance
      jsonPath: .spec.bucketRef
      name: bucket
      type: string
    - description: permissions for this bucket
      jsonPath: .state.permissionsFriendly
      name: permissions
      type: string
    - description: bucket status
      jsonPath: .status.state
      name: status
      type: string
    name: v0alpha
    schema:
      openAPIV3Schema:
        description: An access key for a particular bucket
        properties:
          spec:
            description: Specification for an access key for a particular bucket
            properties:
              bucketRef:
                description: A reference to an existing bucket.
                properties:
                  name:
                    description: The name of the resource
                    type: string
                  namespace:
                    description: The containing namespace.
                    type: string
                required:
                - name
                - namespace
                type: object
              garageRef:
                description: A reference to an existing garage.
                properties:
                  name:
                    description: The name of the resource
                    type: string
                  namespace:
                    description: The containing namespace.
                    type: string
                required:
                - name
                - namespace
                type: object
              permissions:
                description: Permissions associated with the key.
                properties:
                  owner:
                    default: false
                    description: Allow modifying the configuration of a bucket.
                    type: boolean
                  read:
                    default: false
                    description: Allow reading files from a bucket.
                    type: boolean
                  write:
                    default: false
                    description: Allow writing files to a bucket.
                    type: boolean
                type: object
              secretRef:
                description: Set the location of the generated secret.
                properties:
                  name:
                    description: name is unique within a namespace to reference a secret resource.
                    type: string
                  namespace:
                    description: namespace defines the space within which the secret name must be unique.
                    type: string
                type: object
            required:
            - bucketRef
            - garageRef
            - permissions
            - secretRef
            type: object
          status:
            description: The status of an access key.
            nullable: true
            properties:
              permissionsFriendly:
                description: |-
                  A friendly representation of the permissions granted to this key.

                  Format is RWO, where R is read, W is write, and O is owner. Missing permissions show as -.
                type: string
              state:
                description: The current state of the key
                enum:
                - Creating
                - Ready
                type: string
            required:
            - permissionsFriendly
            - state
            type: object
        required:
        - spec
        title: AccessKey
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: garages.deuxfleurs.fr
spec:
  group: deuxfleurs.fr
  names:
    categories: []
    kind: Garage
    plural: garages
    shortNames: []
    singular: garage
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: configured region
      jsonPath: .spec.config.region
      name: region
      type: string
    - description: configured replication mode
      jsonPath: .spec.config.replicationMode
      name: replication
      type: string
    - description: garage capacity
      jsonPath: .status.capacity
      name: capacity
      type: integer
    - description: garage status
      jsonPath: .status.state
      name: status
      type: string
    name: v0alpha
    schema:
      openAPIV3Schema:
        description: A Garage server instance
        properties:
          spec:
            description: Specification for a Garage server instance
            properties:
              autoLayout:
                default: false
                description: |-
                  Whether or not to auto-layout the garage instance

                  Garage has a notion of layouts in order to allow instances to cluster up after the fact. While useful, this generally makes it more difficult to set up without manual intervention.

                  If auto_layout is enabled, the operator will use the configuration supplied in config to automatically layout the garage instance for you.
                type: boolean
              config:
                default:
                  ports:
                    admin: 3903
                    rpc: 3901
                    s3Api: 3900
                    s3Web: 3902
                  region: garage
                  replicationMode: none
                description: |-
                  The config for this garage instance.

                  Most of these options are mirrored from the [official docs](https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/).
                properties:
                  ports:
                    default:
                      admin: 3903
                      rpc: 3901
                      s3Api: 3900
                      s3Web: 3902
                    description: Listening port configuration
                    properties:
                      admin:
                        default: 3903
                        description: Port used for the [admin API](https://garagehq.deuxfleurs.fr/documentation/reference-manual/admin-api/)
                        format: uint16
                        minimum: 0.0
                        type: integer
                      rpc:
                        default: 3901
                        description: Port used for the inter-garage RPC.
                        format: uint16
                        minimum: 0.0
                        type: integer
                      s3Api:
                        default: 3900
                        description: Port used for handling S3 API traffic.
                        format: uint16
                        minimum: 0.0
                        type: integer
                      s3Web:
                        default: 3902
                        description: Port used for hosting buckets as web pages.
                        format: uint16
                        minimum: 0.0
                        type: integer
                    type: object
                  region:
                    default: garage
                    description: |-
                      The [S3 region](https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#s3_region) for this instance.

                      Must be the same when linking up separate instances.
                    type: string
                  replicationMode:
                    default: none
                    description: The type of [replication mode](https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/#replication_mode).
                    type: string
                type: object
              secrets:
                default:
                  admin: null
                  rpc: null
                description: Configuration for where to store the secrets needed for interacting with garage.
                properties:
                  admin:
                    description: Reference to the [admin API](https://garagehq.deuxfleurs.fr/documentation/reference-manual/admin-api/) secret.
                    nullable: true
                    properties:
                      name:
                        description: name is unique within a namespace to reference a secret resource.
                        type: string
                      namespace:
                        description: namespace defines the space within which the secret name must be unique.
                        type: string
                    type: object
                  rpc:
                    description: Reference to the inter-garage RPC secret.
                    nullable: true
                    properties:
                      name:
                        description: name is unique within a namespace to reference a secret resource.
                        type: string
                      namespace:
                        description: namespace defines the space within which the secret name must be unique.
                        type: string
                    type: object
                type: object
              storage:
                description: The storage backing for this garage instance.
                properties:
                  data:
                    description: List of backings to use for storing data.
                    items:
                      description: Reference to a namespaced object
                      properties:
                        name:
                          description: The name of the resource
                          type: string
                        namespace:
                          description: The containing namespace.
                          type: string
                      required:
                      - name
                      - namespace
                      type: object
                    type: array
                  meta:
                    description: Backing to use for storing block metadata.
                    properties:
                      name:
                        description: The name of the resource
                        type: string
                      namespace:
                        description: The containing namespace.
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                required:
                - data
                - meta
                type: object
            required:
            - storage
            type: object
          status:
            description: The status of the garage instance
            nullable: true
            properties:
              capacity:
                description: The total capacity of this instance
                format: int64
                type: integer
              state:
                description: The current state of the garage instance
                enum:
                - Creating
                - LayingOut
                - Ready
                - Errored
                type: string
            required:
            - capacity
            - state
            type: object
        required:
        - spec
        title: Garage
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.deuxfleurs.fr
spec:
  group: deuxfleurs.fr
  names:
    categories: []
    kind: Bucket
    plural: buckets
    shortNames: []
    singular: bucket
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: owning garage instance
      jsonPath: .spec.garageRef
      name: garage
      type: string
    - description: quotas for this bucket
      jsonPath: .spec.quotas
      name: quotas
      type: string
    - description: bucket status
      jsonPath: .status
      name: status
      type: string
    name: v0alpha
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for BucketSpec via `CustomResource`
        properties:
          spec:
            description: A bucket in a garage instance.
            properties:
              garageRef:
                description: A reference to the garage instance for this bucket.
                properties:
                  name:
                    description: The name of the resource
                    type: string
                  namespace:
                    description: The containing namespace.
                    type: string
                required:
                - name
                - namespace
                type: object
              quotas:
                default:
                  maxObjectCount: null
                  maxSize: null
                description: Quotas for this bucket.
                properties:
                  maxObjectCount:
                    description: The maximum amount of objects allowed.
                    format: uint
                    minimum: 0.0
                    nullable: true
                    type: integer
                  maxSize:
                    description: The max size any single file.
                    nullable: true
                    type: string
                type: object
            required:
            - garageRef
            type: object
          status:
            description: The status of a bucket
            enum:
            - Creating
            - Configuring
            - Ready
            - Errored
            nullable: true
            type: string
        required:
        - spec
        title: Bucket
        type: object
    served: true
    storage: true
    subresources:
      status: {}
