---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: garage
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tenant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data-storage
  namespace: garage
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta-storage
  namespace: garage
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
stringData:
  key: admin
kind: Secret
metadata:
  name: garage-admin-manual.key
  namespace: garage
type: Opaque
---
apiVersion: v1
stringData:
  key: f6bb1b389ba63768c64524c00cccc8e54ef88f849af156e86ee5be8498f1c9df
kind: Secret
metadata:
  name: garage-rpc-manual.key
  namespace: garage
type: Opaque
---
apiVersion: deuxfleurs.fr/v0alpha
kind: Garage
metadata:
  name: garage
  namespace: garage
spec:
  autoLayout: true
  config:
    ports:
      admin: 8000
      rpc: 8001
      s3Api: 8002
      s3Web: 8003
    region: garage
    replicationMode: none
  secrets:
    admin:
      name: garage-admin-manual.key
    rpc:
      name: garage-rpc-manual.key
  storage:
    meta: garage-meta-storage
    data:
    - garage-data-storage
---
apiVersion: deuxfleurs.fr/v0alpha
kind: Bucket
metadata:
  name: music
  namespace: tenant
spec:
  garageRef:
    name: garage
    namespace: garage
  quotas:
    maxSize: 5Mi
---
apiVersion: deuxfleurs.fr/v0alpha
kind: AccessKey
metadata:
  name: music-reader
  namespace: tenant
spec:
  bucketRef:
    name: music
    namespace: tenant
  garageRef:
    name: garage
    namespace: garage
  permissions:
    read: true
  secretRef:
    name: music-reader.key
